server:
  port: 0
spring:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      cache-null-values: true
      time-to-live:
        resourceLinks: 300000
  application:
    name: video-streaming-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://cloud-config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config-service
  kafka:
    consumer:
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: false
    listener:
      ack-mode: manual

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

notification-service:
  domain: lb://notification-service
file-service:
  domain: lb://file-service