server:
  port: 8888
spring:
  application:
    name: video-streaming-service
  profiles:
    active: default
  config:
    import: optional:classpath:secret.yaml
#aws credentials
amazon:
  aws:
    accessKey: ${secret.amazon.aws.s3.accessKey}
    secretKey: ${secret.amazon.aws.s3.secretKey}
    region: ${secret.amazon.aws.s3.region}
  s3:
    bucket: ${secret.amazon.aws.s3.bucket}
  cloudfront:
    url: ${secret.amazon.aws.cloudfront.url}
    public-key: ${secret.amazon.aws.cloudfront.public-key}
    secret-key-location: ${secret.amazon.aws.cloudfront.secret-key-location}
