server:
  port: 8888
  servlet:
    context-path: /video-streaming
spring:
  application:
    name: video-streaming-service
  profiles:
    active: default
  config:
    import: optional:classpath:secret.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/video-streaming
    username: nqat0919
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#aws credentials
amazon:
  aws:
    accessKey: ${secret.amazon.aws.s3.accessKey}
    secretKey: ${secret.amazon.aws.s3.secretKey}
    region: ${secret.amazon.aws.s3.region}
  s3:
    bucket: ${secret.amazon.aws.s3.bucket}
  cloudfront:
    url: ${secret.amazon.aws.cloudfront.url}
    public-key: ${secret.amazon.aws.cloudfront.public-key}
    secret-key-location: ${secret.amazon.aws.cloudfront.secret-key-location}
identity-service:
  domain: http://localhost:8080