server:
  port: 18886
spring:
  application:
    name: notification-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://cloud-config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config-service

axon:
  kafka:
    client-id: kafka-axon
    default-topic: notification_topic
    producer:
      retries: 0
      client-id: axon-producer
      bootstrap-servers: localhost:19092
    consumer:
      group-id: "local.event.consumer-group"
      event-processor-mode: subscribing
      bootstrap-servers: localhost:19092
    properties:
      security.protocol: PLAINTEXT

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true