server:
  port: 45551
  servlet:
    context-path: /notification-service
spring:
  application:
    name: notification-service
  cloud:
    stream:
      function:
        definition: userCreationEvent
      bindings:
        userCreationEvent-in-0:
          destination: user_created
          group: notification-service
          contentType: application/json
        userCreationEvent-out-0:
          destination: notification-created
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            spring:
              json:
                trusted:
                  packages: '*'
  data:
    mongodb:
      uri: mongodb://nqat0919:secret@localhost:27018/notifications-db?authSource=admin