server:
  port: 45551
  servlet:
    context-path: /notification-service
spring:
  application:
    name: notification-service
  cloud:
    function:
        definition: userCreationEvent;commentRepliedEvent;dumbass
    stream:
      bindings:
        userCreationEvent-in-0:
          consumer:
            concurrency: 3
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 1
            back-off-max-interval: 10000
          destination: user_created
          group: notification-service
          contentType: application/json
        userCreationEvent-out-0:
          destination: notification_created
          contentType: application/json
          producer:
            partition-key-expression: headers['partitonKey']
            partition-count: 5
        commentRepliedEvent-in-0:
          consumer:
            concurrency: 3
            max-attempts: 5
          destination: comment_replied
          group: notification-service
          contentType: application/json
        commentRepliedEvent-out-0:
          destination: notification_created
          contentType: application/json
      kafka:
        binder:
          brokers:
            - localhost:19092
            - localhost:29092
            - localhost:39092
          consumer-properties:
            spring:
              json:
                trusted:
                  packages: '*'
        bindings:
          commentRepliedEvent-in-0:
            consumer:
              ack-mode: manual_immediate
              start-offset: latest
              enable-dlq: true
              dlq-name: dlq_comment_replied
          userCreationEvent-in-0:
            consumer:
              ack-mode: manual_immediate
              enable-dlq: true
              dlq-name: dlq_user_created
  data:
    mongodb:
      uri: mongodb://nqat0919:secret@localhost:27018/notifications-db?authSource=admin