server:
  port: 18886
spring:
  application:
    name: notification-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://cloud-config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config-service

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true