server:
  port: 18080
logging:
  level:
    springframework:
      security: DEBUG
spring:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      cache-null-values: true
      time-to-live:
        jwtToken: 30000000
  application:
    name: identity-service
  servlet:
    context-path: /identity
  profiles:
    active: default
  config:
    import: optional:configserver:http://cloud-config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config-service
  kafka:
    consumer:
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: false
    listener:
      ack-mode: manual
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

profile-service:
  domain: lb://profile-service
notification-service:
  domain: lb://notification-service
aggregator-service:
  domain: lb://aggregator-service