server:
  port: 8887
  servlet:
    context-path: /comment
spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:33061/comments
    username: nqat0919
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


identity-service:
  domain: http://localhost:8080