version: '3.8'

services:
  mysql-video-streaming:
    container_name: mysql-video-streaming
    image: mysql:8.0.19
    env_file:
      - video-streaming-service/env/mysql.env
      - env/docker-compose.env
    volumes:
      - video-service-mysql-volumes:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password

  mysql-identity:
    container_name: mysql-identity
    image: mysql:8.0.19
    env_file:
      - identity-service/env/mysql.env
    volumes:
      - identity-service-mysql-volumes:/var/lib/mysql
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password

  mysql-comments:
    container_name: mysql-comments
    image: mysql:8.0.19
    env_file:
      - comment-service/env/mysql.env
    volumes:
      - comments-service-mysql-volumes:/var/lib/mysql
    ports:
      - '33061:3306'
    command: --default-authentication-plugin=mysql_native_password

  mysql-notifications:
    container_name: mysql-notifications
    image: mysql:8.0.19
    env_file:
      - notification-service/env/mysql.env
    volumes:
      - notifications-service-mysql-volumes:/var/lib/mysql
    ports:
      - '33062:3306'
    command: --default-authentication-plugin=mysql_native_password

  mysql-profile:
    container_name: mysql-profile
    image: mysql:8.0.19
    env_file:
      - profile-service/env/mysql.env
    volumes:
      - profile-service-mysql-volumes:/var/lib/mysql
    ports:
      - '33063:3306'
    command: --default-authentication-plugin=mysql_native_password

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  redis:
    image: "redis:7.4.0"
    container_name: redis-container
    ports:
      - "6379:6379"

#  jaeger-service:
#    container_name: jaeger-service
#    hostname: jaeger-service
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686"
#      - "14250"
#
#  prometheus:
#    image: prom/prometheus:v2.46.0
#    container_name: prometheus
#    hostname: prometheus
#    command:
#      - --enable-feature=exemplar-storage otlp-write-receiver
#      - --config.file=/etc/prometheus/prometheus.yaml
#    volumes:
#      - ./env/prometheus-config.yaml:/etc/prometheus/prometheus.yaml:ro
#    ports:
#      - "9090:9090"
#  loki:
#    image: grafana/loki:main
#    command: ["-config.file=/etc/loki/local-config-yaml"]
#    ports:
#      - "3100:3100"
#
#  tempo:
#    image: grafana/tempo:2.2.2
#    container_name: tempo
#    hostname: tempo
#    command:
#      - --config.file=/etc/tempo/tempo.yaml
#    volumes:
#      - ./env/tempo-config.yaml:/etc/tempo/tempo.yaml:ro
#    ports:
#      - "3200:3100"
#
#  otel-agent:
#    container_name: otel-agent
#    image: otel/opentelemetry-collector:0.72.0
#    hostname: otel-agent
#    command: [
#      "--config=/etc/otel-config.yaml"
#    ]
#    volumes:
#      - ./env/otel-config.yaml:/etc/otel-config.yaml
#    ports:
#      - "4317:4317"
#      - "55679:55679"
#      - "4318:4318"
#      - "9464:9464"
#    depends_on: [jaeger-service, prometheus]
#
#  grafana:
#    image: grafana/grafana:10.1.0
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#    ports:
#      - "3000:3000"

  broker1:
    container_name: broker1
    image: confluentinc/cp-server:5.4.0
    depends_on: [ zookeeper ]
    env_file:
      - env/broker_1.env
    ports:
      - "19092:19092"

  broker2:
    container_name: broker2
    image: confluentinc/cp-server:5.4.0
    depends_on: [ zookeeper ]
    env_file:
      - env/broker_2.env
    ports:
      - "29092:29092"

  broker3:
    container_name: broker3
    image: confluentinc/cp-server:5.4.0
    depends_on: [ zookeeper ]
    env_file:
      - env/broker_3.env
    ports:
      - "39092:39092"

  debezium:
    image: quay.io/debezium/connect
    hostname: debezium
    container_name: debezium
    env_file:
      - env/debezium.env
    depends_on: [zookeeper, broker1, broker2, broker3]
    ports:
      - "8083:8083"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8081
    ports:
      - 8081:8081
    depends_on: [zookeeper, broker1, broker2, broker3]

volumes:
  video-service-mysql-volumes:
  identity-service-mysql-volumes:
  comments-service-mysql-volumes:
  notifications-service-mysql-volumes:
  profile-service-mysql-volumes:
  data:
    driver: local
  events:
    driver: local