spring:
  application:
    name: eureka-server

#logging:
#  level:
#    io:
#      opentelemetry: DEBUG
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-components: always
#      show-details: always
#  tracing:
#    sampling:
#      probability: 1.0
#  metrics:
#    distribution:
#      percentiles-histogram:
#        enabled: true
#    tags:
#      service: eureka_server
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
#    metrics:
#      export:
#        enabled: true
#        in-memory: true
#        url: http://localhost:4318/v1/metrics

server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true