spring:
  application:
    name: eureka-server

logging:
  level:
    io:
      opentelemetry: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        enabled: false
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true