spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Desktop/my-video-streaming-app
          search-paths: configuration/
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 18181

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true