server:
  port: 8989
spring:
  application:
    name: gateway-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://cloud-config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config-service

gateway-service:
  routes-authorization:
    - path: /identity/users/*
      method: ["PUT", "DELETE"]
      roles: ["ROLE_ADMIN"]

    - path: /video-streaming/videos
      method: ["POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/upvote
      method: ["POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/progress
      method: ["POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/link/*
      method: ["GET"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/files
      method: ["GET", "PUT", "POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/view
      method: [ "POST" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true