server:
  port: 8989
spring:
  application:
    name: gateway-service
  profiles:
    active: default

gateway-service:
  /prefix: /api/v1
  strip: 2
  openEndpoints: >
    /identity/auth/token,
    /identity/auth/introspect,
    /identity/users/registration

identity-service:
  domain: http://localhost:8080
video-streaming-service:
  domain: http://wjbu.online:8888