server:
  port: 8989
spring:
  application:
    name: gateway-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://cloud-config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: cloud-config-service

gateway-service:
  routes-authorization:
    - path: /identity/users/*
      method: ["PUT", "DELETE"]
      roles: ["ROLE_ADMIN"]

    - path: /identity/users/search/id
      method: [ "GET" ]
      roles: [ "ROLE_USER" ]

    - path: /video-streaming/videos
      method: ["POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/up-vote
      method: ["POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/down-vote
      method: ["POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/progress
      method: ["POST"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/link/*
      method: ["GET"]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/upload
      method: [ "PUT" ]
      roles: ["ROLE_USER", "ROLE_ADMIN"]

    - path: /video-streaming/videos/view
      method: [ "POST" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/video/*
      method: ["GET"]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/search/video
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/search/user
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/user/saved
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/video/*/comments
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/comment/*/reply
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/notifications
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /aggregator/query/user/page/*
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /profile/users/follow
      method: [ "PUT" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /profile/users/get/follow/*
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /profile/users/query
      method: [ "POST" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /profile/users/avatar
      method: [ "PUT" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /profile/users/info
      method: [ "PUT" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /profile/users/save/video
      method: [ "POST" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /profile/users/get/avatar
      method: [ "PUT" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /comment/users/new
      method: [ "POST" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /comment/users/video/*
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /comment/users/comment/*/interact
      method: [ "POST" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /comment/users/interacts
      method: [ "POST" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /comment/users/comment/*
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /notification/users
      method: [ "GET" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

    - path: /notification/users/count
      method: [ "POST" ]
      roles: [ "ROLE_USER" ]

    - path: /socket/websocket
      method: [ "GET", "POST", "PUT" ]
      roles: [ "ROLE_USER", "ROLE_ADMIN" ]

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true