spring:
  application:
    name: file-service
#aws credentials
amazon:
  s3:
    bucket: nqat0919-bucket
  cloudfront:
    url: https://cdn.wjbu.online
    public-key: KU831GZ7MVVM1
    secret-key-location: ${USERPROFILE}/cloudfront_private_key.pem
server:
  servlet:
    context-path: /files
  port: 57069
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
