spring:
  application:
    name: file-service
#aws credentials
amazon:
  s3:
    bucket: nqat0919-bucket
  cloudfront:
    url: https://cdn.wjbu.online
    public-key: KELN0DV2RMYI1
    secret-key-location: ${HOME}/resource/pk-APKAZQ3DSOCM42AQIJCR.pem
server:
  servlet:
    context-path: /files