version: '3.8'

services:
  mysql:
    container_name: mysql-database
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
      - ./env/docker-compose.env
    volumes:
      - video-service-mysql-volumes:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  video-service-mysql-volumes: