spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
gateway-service:
  /prefix: /api/v1
  strip: 2
  openEndpoints: >
    /identity/auth/token,
    /identity/auth/introspect,
    /identity/users/registration

identity-service:
  domain: lb://identity-service
video-streaming-service:
  domain: http://wjbu.online:8888
comment-service:
  domain: lb://comment-service