spring:
#  sleuth:
#    otel:
#      config:
#        trace-id-ratio-based: 1.0
#      exporter:
#        otlp:
#          endpoint: http://collector:4317
gateway-service:
  /prefix: /api/v1
  strip: 2
  openEndpoints: >
    /identity/auth/token,
    /identity/auth/introspect,
    /identity/users/registration,
    /identity/auth/refresh,
# Test purpose only:
    /socket/websocket/send,

identity-service:
  domain: lb://identity-service
video-streaming-service:
  domain: lb://video-streaming-service
comment-service:
  domain: lb://comment-service
profile-service:
  domain: lb://profile-service
aggregator-service:
  domain: lb://aggregator-service
socket-service:
  domain: lb://socket-service
notification-service:
  domain: lb://notification-service