receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-service:14250
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: otelcol

service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging, jaeger ]
    metrics:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ prometheus ]